//
// Copyright 2020 Acoustic, L.P.
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

import Foundation

/**
 * Represents content item  that can be retrieved using delivery search API.
 */
public struct ContentItem: Document {
    /**
     * The identifier of the item. For items of the same "classification", this identifier is unique.
     * The combination of the "classification" and the "id" is unique across all items of the Watson Content Hub tenant.
     */
    public let id: String
    
    /**
     * The name of the item.
     */
    public let name: String
    
    /**
     * This field describes the kind of item. The value that is returned can be "asset", "category", "content" or "taxonomy".
     */
    public let classification: String
    
    /**
     * The last modification date of the item.
     *
     * #### Examples:
     * ```
     * 2020-01-07T17:52:31.610Z
     * 2020-01-07T17:52:31.477Z
     * 2020-01-07T17:52:31.828Z
     * ```
     */
    public let lastModified: String
    
    /**
     * The UUID of the user that last modified the item.
     */
    public let lastModifierId: String
    
    /**
     * The creation date of the item.
     *
     * #### Examples:
     * ```
     * 2020-01-07T17:52:31.610Z
     * 2020-01-07T17:52:31.477Z
     * 2020-01-07T17:52:31.828Z
     * ```
     */
    public let created: String
    
    /**
     * The UUID of the user that created the item.
     */
    public let creatorId: String
    
    /**
     * Field can contain boolean element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let boolean1: [Bool]?
    
    /**
     * Field can contain boolean element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let boolean2: [Bool]?
    
    /**
     * The list of all category selections for the content.
     * All category selection elements on content are merged into this property.
     */
    public let categories: [String]?
    
    /**
     * The list of all leaf category selection elements for the asset or content.
     */
    public let categoryLeaves: [String]?
    
    /**
     * Field can contain date element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     *
     * #### Examples:
     * ```
     * 2020-01-07T17:52:31.610Z
     * 2020-01-07T17:52:31.477Z
     * 2020-01-07T17:52:31.828Z
     * ```
     */
    public let date1: [String]?
    
    /**
     * Field can contain date element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     *
     * #### Examples:
     * ```
     * 2020-01-07T17:52:31.610Z
     * 2020-01-07T17:52:31.477Z
     * 2020-01-07T17:52:31.828Z
     * ```
     */
    public let date2: [String]?
    
    /**
     * Field contains the full JSON document for the item.
     */
    public let document: [String: Any]?
    
    /**
     * For pages, this field contains all kinds a page is assigned to.
     */
    public let kind: [String]?
    
    /**
     * The description of the item.
     */    
    public let description: String?
    
    /**
     * The list of tags assigned to the item.
     */
    public let tags: [String]?
    
    /**
     * Field contains the list of path values related to files that are generated by pre-rendering the item.
     */
    public let generatedFiles: [String]?
    
    /**
     * Field specifies whether the content is managed or not managed and whether the asset is a managed asset or a so-called non-managed web asset.
     */
    public let isManaged: Bool
    
    /**
     * Field contains an array of strings.
     * Each string consists of the latitude and the longitude of location elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let location1: [String]?
    
    /**
     * Field contains an array of strings.
     * Each string consists of the latitude and the longitude of a Location element of the content item.
     * For example, this field contains ["48.666259, 9.039273", "53.418880, -6.416081"] for a content item with two Location elements.
     */
    public let locations: [String]?
    
    /**
     * Field can contain number element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let number1: [Double]?
    
    /**
     * Field can contain number element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let number2: [Double]?
    
    /**
     * Field contains the state the item is in.
     * The value of this field can be "ready" or "retired".
     */
    public let status: String
    
    /**
     * Field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let string1: [String]?
    
    /**
     * Field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let string2: [String]?
    
    /**
     * Field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let string3: [String]?
    
    /**
     * Field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let string4: [String]?
    
    /**
     * Field can contain a single date element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableDate1: String?
    
    /**
     * Field can contain a single date element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableDate2: String?
    
    /**
     * Field can contain a single number element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableNumber1: String?
    
    /**
     * Field can contain a single number element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableNumber2: String?
    
    /**
     * Field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableString1: String?
    
    /**
     * Field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableString2: String?
    
    /**
     * Field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableString3: String?
    
    /**
     * Field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    public let sortableString4: String?
    
    /**
     * Field is a collection of field names and text fragments that make up the item.
     * It facilitates full-text search.
     */
    public let text: [String]
    
    /**
     * Field contains the name of the content type.
     */
    public let type: String
    
    /**
     * Field contains the ID of the content type.
     */
    public let typeId: String
}

extension ContentItem: Classifiable {
    public static let classification: DocumentClassification? = .content
}
